tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🧹 Cleaned or removed features'
    label: 'remove'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📝 Documentation'
    labels:
      - 'doc'
      - 'documentation'
  - title: '🚦 Tests'
    labels:
      - 'test'
      - 'tests'
change-template: '- #$NUMBER: $TITLE'
template: |
  ## What’s Changed Since Last Release $NEXT_PATCH_VERSION
  $CHANGES
